# Generated by Django 4.1.2 on 2022-10-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(default='None', max_length=20)),
                ('pet_name', models.CharField(default='None', max_length=50)),
                ('birthday', models.DateField(default='None')),
                ('pet_age', models.IntegerField(default='None')),
                ('pet_high', models.IntegerField(default='None')),
                ('pet_weight', models.IntegerField(default='None')),
                ('pet_passport_number', models.IntegerField(default='None')),
                ('pet_passport', models.BooleanField(default='None')),
            ],
        ),
    ]
