# Generated by Django 4.1.2 on 2022-10-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_age',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='pet_passport',
        ),
    ]
