# Generated by Django 4.1.2 on 2022-10-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_remove_pet_pet_age_remove_pet_pet_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_high',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_passport_number',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_type',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_weight',
            field=models.IntegerField(default=''),
        ),
    ]
