# Generated by Django 4.1.2 on 2022-10-31 14:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_alter_pet_birthday_alter_pet_pet_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(default='', help_text='формат: ГГГГ-ММ-ДД', validators=[django.core.validators.RegexValidator('^[1-2]\\d{3}-[0-1]\\d-[0-3]\\d$')]),
        ),
    ]
