# Generated by Django 4.1.2 on 2022-10-31 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_alter_pet_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birthday',
            field=models.DateField(default='', validators=[django.core.validators.RegexValidator('^[1-2]\\d{3}-[0-1]\\d-[0-3]\\d$')]),
        ),
    ]
